### ISSUE TITLE
Propose replacing HTTP::Tiny with HTTP::Thin

### ISSUE THREAD

**Issue by markstos** [kaare/Role-REST-Client#25]
Role::REST::Client appears to have the intent to support other user agents besides HTTP::Tiny, but in practice it requires HTTP::Tiny's uncommon call signature to the `request()` method for compatibility. 

Role::REST::Client also contains some code to handle the case where a user agent returns a hashref like HTTP::Tiny vs the more common HTTP::Request objects. 

I propose updating the internals to use [HTTP::Thin](https://metacpan.org/module/HTTP::Thin) as the default user agent instead of HTTP::Tiny.  HTTP::Thin sub-classes HTTP::Tiny and just wraps it's `request` method, so that it can accept a `HTTP::Request` object as input, like LWP::UserAgent-compatible user agents, and it also returns a `HTTP::Response` object like LWP::UserAgent-compatible agents. 

This has a couple of advantages, while still retaining the bulk of performance and simplicity of HTTP::Tiny:
1. All LWP::Useragent-compatible agents can now be used as alternatives for those that want or need them.
2. A bit of internal code can be simplified as we can now expect all user agents to follow the convention of returning an `HTTP::Response` object directly. 

@kaare: What do you think?

**Comment by abraxxa** [comment]
Version 0.16 included this change, please close the issue.

**Comment by markstos** [comment]
Confirmed to be fixed in 2013: https://metacpan.org/release/KAARE/Role-REST-Client-0.23/source/Changes#L28
