### ISSUE TITLE
Feature Request: Send options to serializer

### ISSUE THREAD

**Issue by gerhardj** [kaare/Role-REST-Client#30]
Hey, I need my deserialized object in a specific format. Therefore I need to have serializer set-up like follows:

``` perl
my $s = Data::Serializer::Raw->new(
    serializer => 'XML::Simple',
    options    => { RootName => 'object' } );
```

Could there be an option to add custom config options to the serializer object?

**Comment by kaare** [comment]
Can you try the new serializer_options ?

**Comment by gerhardj** [comment]
It does work. The syntax needs some getting used to, because of so many layers. Usage as a role now looks like this (this works for me):

```perl
has '+serializer_options' => (default => sub {
        my $s = Data::Serializer::Raw->new(
            serializer => 'XML::Simple',
            options    => { RootName => 'object' } );
        return { serializer  => $s };
    });
```
